; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 19 2022 14:10:59 GMT-0700 (Mountain Standard Time)
; ================================================================================

DATAYMVTUWWL3N:
	dc.w DATAYMVTUWWL3N_0-DATAYMVTUWWL3N, DATAYMVTUWWL3N_1-DATAYMVTUWWL3N
	dc.w DATAYMVTUWWL3N_2-DATAYMVTUWWL3N
DATAYMVTUWWL3N_0: dc.b $1
	dc.b $FC, $5, $0, $6, $F8
DATAYMVTUWWL3N_1: dc.b $1
	dc.b $FC, $5, $0, $A, $F8
DATAYMVTUWWL3N_2: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
	even