; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 19 2022 14:27:20 GMT-0700 (Mountain Standard Time)
; ================================================================================

DATALFJW6T9HMA:
	dc.w DATALFJW6T9HMA_0-DATALFJW6T9HMA, DATALFJW6T9HMA_1-DATALFJW6T9HMA
	dc.w DATALFJW6T9HMA_2-DATALFJW6T9HMA
DATALFJW6T9HMA_0: dc.b $1
	dc.b $F4, $6, $0, $6, $F8
DATALFJW6T9HMA_1: dc.b $1
	dc.b $F4, $6, $0, $C, $F8
DATALFJW6T9HMA_2: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
	even