; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 19 2022 13:57:06 GMT-0700 (Mountain Standard Time)
; ================================================================================

DATA4KU7D1TZTXA:
	dc.w DATA4KU7D1TZTXA_0-DATA4KU7D1TZTXA, DATA4KU7D1TZTXA_1-DATA4KU7D1TZTXA
	dc.w DATA4KU7D1TZTXA_2-DATA4KU7D1TZTXA, DATA4KU7D1TZTXA_3-DATA4KU7D1TZTXA
	dc.w DATA4KU7D1TZTXA_4-DATA4KU7D1TZTXA, DATA4KU7D1TZTXA_5-DATA4KU7D1TZTXA
	dc.w DATA4KU7D1TZTXA_6-DATA4KU7D1TZTXA, DATA4KU7D1TZTXA_7-DATA4KU7D1TZTXA
	dc.w DATA4KU7D1TZTXA_8-DATA4KU7D1TZTXA, DATA4KU7D1TZTXA_9-DATA4KU7D1TZTXA
	dc.w DATA4KU7D1TZTXA_A-DATA4KU7D1TZTXA, DATA4KU7D1TZTXA_B-DATA4KU7D1TZTXA
	dc.w DATA4KU7D1TZTXA_C-DATA4KU7D1TZTXA
DATA4KU7D1TZTXA_0: dc.b $6
	dc.b $EC, $1, $0, $A, $E4
	dc.b $EC, $5, $0, $C, $C
	dc.b $FC, $E, $20, $10, $E4
	dc.b $FC, $E, $20, $1C, $4
	dc.b $14, $C, $20, $28, $EC
	dc.b $14, $0, $20, $2C, $C
DATA4KU7D1TZTXA_1: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $2, $EC
DATA4KU7D1TZTXA_2: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATA4KU7D1TZTXA_3: dc.b $3
	dc.b $E4, $8, $0, $3D, $F4
	dc.b $EC, $9, $0, $40, $EC
	dc.b $EC, $5, $0, $46, $4
DATA4KU7D1TZTXA_4: dc.b $3
	dc.b $E4, $8, $0, $4A, $F4
	dc.b $EC, $9, $0, $4D, $EC
	dc.b $EC, $5, $0, $53, $4
DATA4KU7D1TZTXA_5: dc.b $3
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATA4KU7D1TZTXA_6: dc.b $3
	dc.b $E4, $4, $0, $64, $4
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATA4KU7D1TZTXA_7: dc.b $4
	dc.b $E4, $9, $0, $66, $F4
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATA4KU7D1TZTXA_8: dc.b $1
	dc.b $4, $5, $0, $2D, $22
DATA4KU7D1TZTXA_9: dc.b $1
	dc.b $4, $5, $0, $31, $22
DATA4KU7D1TZTXA_A: dc.b $0
DATA4KU7D1TZTXA_B: dc.b $2
	dc.b $0, $8, $1, $2A, $22
	dc.b $8, $8, $11, $2A, $22
DATA4KU7D1TZTXA_C: dc.b $2
	dc.b $F8, $B, $1, $2D, $22
	dc.b $0, $1, $1, $39, $3A
	even